### PR TITLE
Fix #1 #28 #29 #30 #31 #32 #33

### LINKED ISSUE #1: Dynamic table creating
create table when data load to BigQuery.

For example [fluent-plugin-bigquery](https://github.com/kaizenplatform/fluent-plugin-bigquery) support [3method](https://github.com/kaizenplatform/fluent-plugin-bigquery#dynamic-table-creating).
1. List fields in config.yml
2. ~~Load a schema file in JSON.~~ implemented
3. ~~Fetch a schema using BigQuery API~~ implemented at [v0.2.2](https://github.com/embulk/embulk-output-bigquery/blob/master/CHANGELOG.md#022---2016-02-15)

in  embulk-output-bigquery...as follows?
## ~~load schema from json file~~ implemented

```
out:
  type: bigquery
  auto_create_table: true
  table: target_table
  schema_path: /path/to/schema.json
```
## load from config.yml

```
out:
  type: bigquery
  auto_create_table: true
  table: target_table
  schema: id:integer, name:string, time:timestamp
```
## ~~fetch_schema~~ implemented at [v0.2.2](https://github.com/embulk/embulk-output-bigquery/blob/master/CHANGELOG.md#022---2016-02-15)

```
out:
  type: bigquery
  fetch_schema: true
```
## load from embulk schema?

But, FileOutputPlugin may not be received schema from embulk.
And support for NULLABLE/REQUIRED/REPEATED field is difficult.

```
out:
  type: bigquery
  auto_create_table: true
  table: target_table
  schema: 
```

### LINKED ISSUE #28: [ISSUE] LOAD takes lots of time with ScatterTransactionalPageOutput
With embulk 0.8, page scattering is introduced http://www.embulk.org/docs/release/release-0.8.0.html. 

It seems that because of this (maybe), embulk-output-bigquery now works as follows:
1. creates local files with number of scatterCount
2. LOAD local files of scatterCount **sequentially**

In an environment like 24 CPU core, embulk-output-bigquery issues 24 LOADS sequentially even for, say, 100 lines of data. 1 LOAD takes about 100 sec, thus 40min totally for 100 lines.

### LINKED ISSUE #29: [Feature Request] Want to validate schema.json as soon as possible
Currently, we get errors of schema.json at LOAD, i.e., after generating all of local files. 
That is, if we take an hour to generate local files, we can notice errors of schema.json after an hour passed. 

I want to notice such errors as soon as possible.

### LINKED ISSUE #30: [Feature Request] Want to notice data error as soon as possible
Currently, we get errors of data at LOAD after generating all of local files. 
That is, if we take an hour to generate local files, we can notice errors of data after an hour passed.

I want to notice such errors as soon as possible.

### LINKED ISSUE #33: Plugin should retry executeLoad method if catches SocketTimeOutException
This stacktrace is of embulk-output-bigquery v0.1.11, but same problem may happen with recent version.

``` shell
2016-02-24 00:22:16.178 +0000 [INFO] (transaction): Loaded plugin embulk-output-bigquery (0.1.11)
2016-02-24 00:22:18.713 +0000 [INFO] (task-0000): Writing file [/path/to/.000.00.csv.gz]
2016-02-24 00:22:19.083 +0000 [INFO] (task-0000): Job preparing... project:my-project dataset:my-dataset table:my-table
2016-02-24 00:22:19.093 +0000 [INFO] (task-0000): table:[my-table] will be create if not exists
2016-02-24 00:22:19.107 +0000 [INFO] (task-0000): Upload start [/path/to/.000.00.csv.gz]
2016-02-24 00:22:39.143 +0000 [ERROR] (task-0000): Read timed out
2016-02-24 00:22:39.144 +0000 [INFO] (transaction): {done:  1 / 1, running: 0}
java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
    at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:363)
    at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:572)
    at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:374)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:370)
    at org.embulk.spi.Exec.doWith(Exec.java:25)
    at org.embulk.exec.BulkLoader.run(BulkLoader.java:370)
    at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
    at com.treasuredata.worker.calls.EmbulkResult.run(EmbulkResult.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.treasuredata.java_call.JavaCall.processRequest(JavaCall.java:147)
    at com.treasuredata.java_call.JavaCall.run(JavaCall.java:111)
    at com.treasuredata.worker.JavaCallMain.main(JavaCallMain.java:21)
Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at org.embulk.output.BigqueryOutputPlugin$2.finish(BigqueryOutputPlugin.java:323)
    at org.embulk.standards.GzipFileEncoderPlugin$1.finish(GzipFileEncoderPlugin.java:62)
    at org.embulk.spi.util.OutputStreamFileOutput.finish(OutputStreamFileOutput.java:58)
    at org.embulk.spi.util.FileOutputOutputStream.close(FileOutputOutputStream.java:104)
    at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
    at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
    at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
    at java.io.BufferedWriter.close(BufferedWriter.java:266)
    at org.embulk.spi.util.LineEncoder.finish(LineEncoder.java:100)
    at org.embulk.standards.CsvFormatterPlugin$1.finish(CsvFormatterPlugin.java:206)
    at org.embulk.spi.FileOutputRunner$DelegateTransactionalPageOutput.finish(FileOutputRunner.java:172)
    at org.embulk.spi.PageBuilder.finish(PageBuilder.java:223)
    at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:154)
    at org.embulk.spi.util.Executors.process(Executors.java:67)
    at org.embulk.spi.util.Executors.process(Executors.java:42)
    at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:104)
    at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:100)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    Suppressed: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END
        at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:968)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:554)
        at sun.nio.cs.StreamEncoder.flushLeftoverChar(StreamEncoder.java:242)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:301)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at org.embulk.spi.util.LineEncoder.close(LineEncoder.java:114)
        at org.embulk.standards.CsvFormatterPlugin$1.close(CsvFormatterPlugin.java:211)
        at org.embulk.spi.FileOutputRunner$DelegateTransactionalPageOutput.close(FileOutputRunner.java:178)
        at org.embulk.spi.CloseResource.close(CloseResource.java:34)
        at org.embulk.spi.util.Executors.process(Executors.java:81)
        ... 7 more
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
    at sun.security.ssl.InputRecord.read(InputRecord.java:480)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:689)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeUploadInitiation(MediaHttpUploader.java:519)
    at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:384)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
    at org.embulk.output.BigqueryWriter.executeLoad(BigqueryWriter.java:181)
    at org.embulk.output.BigqueryOutputPlugin$2.finish(BigqueryOutputPlugin.java:315)
```

### PR DESCRIPTION
**Pull request by sonots**
I rewrote the plugin (but, in jruby) entirely. I send this PR because @sakama said my branch can be a master. The gem version is now v0.3.0.pre1.

ref. https://github.com/sonots/embulk-output-ruby_bigquery
# NEW FEATURES
## Support parallel LOADs

Fix #28. The new version supports parallel LOADs of intermediate local files.

With an experiment with 120 million records and 24 CPU core environments (one gzip file size was about 100MB), I got experimental results as follows:
- Sequential load: 92 min
- Parallel Load: 6 min

Parallel LOADs would introduce network traffic issue, but it can be resolved with `max_load_parallels` option as described below.
## Create table first

Fix #29. The new version explicitly creates a table at an early stage without using the feature of LOAD job. 
This enables us to notice schema.json errors as early stage as possible.
## Rehearsal Mode

Fix #30. Added option `with_rehearsal true`. With this modes, `rehearsal_counts` (default: 1000) records are uploaded into REHEARSAL temporary table, and finally drop the table. This enables us to investigate data errors as early stage as possible. 
## Support google-api-ruby-client request options

timeout_sec, open_timeout_sec, retries options are added. `retries` option fixes #33.
## Continue from file generation

With `delete_from_local_when_job_end false` and newly added `skip_file_generation true` option, we can skip file generation and reuse the intermediate local files to LOAD into BigQuery.
## Auto table creation from Embulk schema

Fix #1. BigQuery table schema is automatically defined from Embulk schema. It can be customized with `column_options`.
## Auto create dataset

With `auto_create_dataset true`, a dataset is automatically created if it does not exist.
## Support transactional append

Now mode `append` is a transactional append, and `append_direct` is the one which is not transactional.
# NOTICE
## Network Traffic Issue

Since the new version supports parallel LOADs, multiple files are uploaded in parallel and consumes network traffic. 
With 24 100MB files (that is, 24 concurrency), network traffic was about 500Mbps in the experimented environment.

~~The number of concurrency can be configured with `max_load_parallels` option.~~ `max_load_parallels` option was dropped for difficulty of support in map reduce executor. 
## Formatter Performance Issue

Since the new version is written as a jruby plugin, the performance to format records into csv or jsonl is slow. 

Here is my experimental results to generate local files for 120 million records with old plugin and new plugin. 
- Java version: 14 min
- Jruby version: 22 min

To resolve this issue, we can use another filter plugin written in Java to format records such as [embulk-filter-to_json](https://github.com/civitaspo/embulk-filter-to_json) as:

```
filters:
  - type: to_json
    column: {name: json_payload, type: string}
    default_timezone: UTC
    default_format: "%Y-%m-%d %H:%M:%S.%N"
out:
  type: bigquery
  payload_column: json_payload
  source_format: NEWLINE_DELIMITED_JSON
  compression: GZIP
  …
```

The result is as below, as you can see, this is not big issue anymore. 
- Jruby version with embulk-filter-to_json: ~~15min~~ 14min
## Performance comparison

As a summary, with 120 million records and 24 CPU core (input is [embulk-input-vertica](https://github.com/sonots/embulk-input-vertica)):
- Old version
  - CPU usage: 300% in average (during file generation)
  - Network traffic: 25Mbps in average (during upload)
  - Elapsed time (file generation): 14min
  - Elapsed time (total): 107min
- New version without embul-filter-to_json
  - CPU usage: 1500% in average (during file generation)
  - Network traffic: 500Mbps in average (during upload)
  - Elapsed time (file generation): 22min
  - Elapsed time (total): 28min
- New version with embulk-filter-to_json
  - CPU usage: 400% in average (during file generation)
  - Network traffic: 500Mbps in average (during upload)
  - Elapsed time (file generation): ~~15min~~ 14min
  - Elapsed time (total): 21min

gzip compression is enabled on all of them.

### CODE REVIEW

**Comment by frsyuki** [comment]
First of all, good job :+1: 
But before going into the implementation, there are several design problems for us to merge this code...
- We use mapreduce executor. This PR assumes that all `run` tasks and `transaction` method run on the same machine. Although existent implementation also assumes it, adding features or behaviors depending on it such as `max_load_parallels` is not very acceptable our use case if we consider future support and backward compatibility.
- To solve this problem, available options we have are:
  - 1) Call LOAD command at `run` but parallelize it. 2 updates: a) digdag parallelize finish. b) run parallelize LOAD. run method creates a background thread and a queue. run method builds files and pushes them to the queue. The background thread gets all files from the queue, clear the queue, loads them to BQ, and repeats this.
  - 2) Upload files to GCS in parallel at run method and loads them to BQ at the end of transaction.
  - I think 1) can be the default. 2) can be enabled if GCS bucket name is set.
- Users need to consider consistency of configuration between filter and output. This seems hard for us to support users. Detection of misconfiguration becomes also hard because wrong source_format loads broken data silently. A better solution is to instantiate filter plugin within output plugin, or write the entire output plugin in Java.

**Comment by sonots** [comment]
> `run` method

What is that? Can jruby output plugin have `run` method? How does it work?

> A better solution is to instantiate filter plugin within output plugin, 

Is it possible to instantiate java filter plugin in jruby output plugin?

> We use mapreduce executor
> max_load_parallels is not very acceptable our use case

I am not using `max_load_paralles` yet (24 parallel uploads consumes 500Mbps and it is acceptable yet), so I can drop this option for now.

**Comment by sonots** [comment]
> max_load_parallels is not very acceptable our use case

Dropped `max_load_parallels` option

> Users need to consider consistency of configuration between filter and output.

~~`payload_column` option is now a boolean option and assumes 1st column as a payload column. This is enough for use with filter-to_json, or parser-none. This gives a restriction, but also gives a easier configuration for users.~~

`payload_column_index` option is newly added. Usually specifying as `payload_column_index: 0` is fine enough.

**Comment by frsyuki** [comment]
@sonots thank you for waiting for this long reviewing process. @muga and I had a review meeting here in the US to discuss how we can cooperate with your team and contribute this project.

> Dropped max_load_parallels option

Thank you. This is helpful. MapReduce executor is important in our use case of Embulk.
Using local file is a related concern. I mentioned before, sing GCS is the best for this BQ output plugin. However, we came up with another option: "shared temporary files" API

Idea of Embulk's "shared temporary files" API: tasks ("open" method in output plugin, "run" method in input plugin) can put files there and transaction can read them. Implementation of it is provided by executor plugin. If local executor plugin is used, local file system is used. If MR executor plugin is used, HDFS is used.

This is still just an idea but with this way, we don't have to change architecture of this PR drastically to support MR executor.

The other concern is combination with filter plugin:
Plugins should be usable as standalone in Embulk. This PR recommends users to use filter plugin and `source_format` option for performance optimization (otherwise CPU load is much higher).
To improve this, we can implement the JSON formatting logic in Java as a gem with java extension, and call it from this plugin. This idea solves this concern. So, please be prepared for this future change.

@sakama: As above, there're ideas to solve the concerns later. So, I think this is good to merge now. Any ideas in your mind? Why don't you merge?

**Comment by sonots** [comment]
@sakama Could you give a right to commit this repository and release a new gem? You can add me to gem owner as

```
gem owner embulk-output-bigquery -a xxxxxx
```

**Comment by sakama** [comment]
@sonots I added you to gem owner
https://rubygems.org/gems/embulk-output-bigquery

**Comment by sonots** [comment]
Merged! Thanks!

**Comment by sonots** [comment]
v0.3.0.pre1 is released!

**Comment by sakama** [comment]
thanks! sorry I took long time to review.

**Pull request merged**
