### PR TITLE
Make `write_disposition` configurable

### PR DESCRIPTION
**Pull request by joker1007**
I often want to use `WRITE_TRUNCATE` mode.
This PR add `write_disposition` option and enable to config it.

### CODE REVIEW

**Comment by sakama** [comment]
Thank you for your pull-request.

There is one thing to be considered.
Embulk can execute multiple tasks as BigQuery's job at the same time.

If task is single, your code should work fine. But when multiple tasks is executed, it will work like...

| task No. | is expected behavior? |
| --- | :-: |
| task**0**(WRITE_TRUNCATE) | Yes |
| task**1**(WRITE_TRUNCATE) | No. we lost task0's data |
| task**2**(WRITE_TRUNCATE) | No. we lost task1's data |
| task**3**(WRITE_TRUNCATE) | No. we lost task2's data |

So we have to set `writeDisposion=truncate` to only one of these tasks(jobs) that will end up first.
But Embulk couldn't know which task(job) will end first.
- expected behavior
  task**0**(WRITE_TRUNCATE)
  task**1**
  task**2**
  task**3**
- the worst behavior
  task**3**
  task**1**
  task**2**
  task_0_(WRITE_TRUNCATE) lost all inserted data.

**Comment by joker1007** [comment]
`Embulk can execute multiple tasks` means that multiple embulk processes are launchd at the same time and order of them is ambiguous, isn't it?

I didn't considered it.
But I think that it is not serious probrem.
When I want to use `WRITE_TRUNCATE`,
each query is idempotent, or result set of the query includes past record.
Even in other case, Workflow Engine can resolve the probrem (like airflow, digdag).

**Comment by sakama** [comment]
> Embulk can execute multiple tasks means that multiple embulk processes are launchd at the same time and order of them is ambiguous, isn't it?

No, I meant number of tasks in each Embulk processes, not about Embulk process itself.

For example, when I have 3 input files,

```
sample_01.csv
sample_02.csv
sample_03.csv
```

and I execute Embulk with following config.yml...

``` yml
in
  type: file
  path_prefix: /path/to/sample
  parser:
    type: csv
    ...
out
  type: bigquery
  ...
```

I will get 3 tasks in this Embulk process.
Because number of task of Embulk depends on number of input files.

As you says, Embulk process itself can be managed by workflow engine.

**Comment by sakama** [comment]
One idea to implement `writeTruncate` easily is send truncate request at [transaction()](https://github.com/embulk/embulk-output-bigquery/blob/v0.1.11/src/main/java/org/embulk/output/BigqueryOutputPlugin.java#L148) method.

``` java
// This method will be executed only once
public ConfigDiff transaction(...)
{    
    // Send truncate request to BigQuery
}

// This method will be called as same as task count
public TransactionalFileOutput open(...)
{
    public void finish()
    {
        // Insert BigQuery's Job
        // Already exists
        bigQueryWriter.executeLoad(project, dataset, table, filePath);
    }
}
```

## Problems of this approach

The time that table does not exists will appear until inserted job will finish.
So we might have to add `replace` mode like embulk-output-jdbc to decrease downtime.
1. Create new table with temporary name
2. Insert data
3. Rename old table to something others
4. Rename new table to old table's name.

**Comment by joker1007** [comment]
OK, I see. It's difficult probrem.
I understand reason why `write_disposition` is not configurable.

I thinked about same idea.
I can add `delete_table_before_load` option.
As you says, the option makes table not exist until plugin finishes to load data, but it is often useful for me.

And I thinked about `replace` mode too.
But bigquery tables cannot rename.
`replace` mode process is like following:
1. Create new table with temporary name
2. Insert data
3. Invoke job of Copy old table to something others (omittable if backup is unnecessary)
4. Delete old table
5. Invoke job of Copy new table to old table's name
6. Delete backup table

I think that copy job is faster than load job probably.

**Comment by sakama** [comment]
> But bigquery tables cannot rename

oh... I misunderstood.

I'll try to implement `replace mode` in few weeks.
Please give me some time.

**Comment by joker1007** [comment]
@sakama 
I tried to implement `replace mode`.
Please review the code. And I would like to get your feedback.

**Comment by joker1007** [comment]
I closes this pr. Because #20 is merged.

**Pull request closed without merging**
