### PR TITLE
Support schemaUpdateOptions

### PR DESCRIPTION
**Pull request by sonots**

### CODE REVIEW

**Comment by sonots** [comment]
0.4.1 is released

**Comment by liujidong** [comment]
hi,
I set the schema_update_options: [ALLOW_FIELD_ADDITION, ALLOW_FIELD_RELAXATION] in the yml.liquid file
but it did't work!
any help?
thanks a lot

**Comment by sonots** [comment]
How did not it work? Could you describe details?

**Comment by sonots** [comment]
And, could you paste your debug log? You can see whether the option is specified or not.

**Comment by liujidong** [comment]
I import data to bigquery from redshift, the redshift tables have new columns 
the error logs below:
 errors:[{:reason=>"invalid", :mess
age=>"Provided Schema does not match Table vuclipdataflow-1301:amplitude_140681_
new.events140681_5826646."}]
what's the problem?
how I check the output plugin version by the way?

**Comment by sonots** [comment]
It looks the option is specified correctly.
BigQuery returns the error message if given schema and the table schema does match.
BigQuery unkindly does not tell us what does not match, though.

**Comment by liujidong** [comment]
does this option can auto add new columns to bigquery by schema read from redshift?
why dose not it work?
I diff the two schema and found 4 new columns!

**Comment by sonots** [comment]
Adding new columns should work based on my experiment.

> schema read from redshift?

I do not know how you are doing this. Look your debug log carefully, I can tell nothing because I have no further information.

**Comment by liujidong** [comment]
I updated the plugin output-bigquery to 0.4.1
but there is another error:
Error: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `[]
=' for nil:NilClass
and my config:
  schema_update_options: [ALLOW_FIELD_ADDITION, ALLOW_FIELD_RELAXATION]
is there something wrong?
I checked your examples,there are 2 types:
1:schema_update_options: [ALLOW_FIELD_ADDITION, ALLOW_FIELD_RELAXATION]
2:schema_update_options: 
     -ALLOW_FIELD_ADDITION
     -ALLOW_FIELD_RELAXATION]
which one is right?

**Comment by sonots** [comment]
I can not reproduce. Could you show me your entire config and execution log?

```
schema_update_options: [ALLOW_FIELD_ADDITION, ALLOW_FIELD_RELAXATION]
```

```
schema_update_options: 
  - ALLOW_FIELD_ADDITION
  - ALLOW_FIELD_RELAXATION
```

Both is correct.

**Comment by sonots** [comment]
Ah, I got you. Fixed and released 0.4.2. Could you try with it?

**Comment by liujidong** [comment]
I updated to 0.4.2 and got errors like this:

Error: org.jruby.exceptions.RaiseException: (Error) failed to load /tmp/embulk_o
utput_bigquery_20161012-16457-fal157.16457.11928.csv.gz to vuclipdataflow-1301:a
mplitude_140681_new.LOAD_TEMP_45095620_c6a8_472c_8f69_d246ec00a3a3_events140681_
5826646, response:{:status_code=>409, :message=>"duplicate: Already Exists: Job
vuclipdataflow-1301:embulk_load_job_e5810dd5495d5c435a5fde07b310f097", :error_cl
ass=>Google::Apis::ClientError}

**Comment by sonots** [comment]
Hmm, it is wierd. temp table is created randomly, so it should not duplicate.

Why don't you paste your config?

**Comment by liujidong** [comment]
**my config:**

```
out:
  type: bigquery
  mode: append
  #is_skip_job_result_check: true
  auth_method: json_key
 json_keyfile:...
project: vuclipdataflow-1301
  max_bad_records: 0
  #dataset: viu_data_warehouse
  dataset: amplitude_140681_new
  auto_create_table: true
  table: {{ env.embulk_table }}
  compression: GZIP
  source_format: CSV
  default_timezone: 'UTC'
  escape: "\\"
  delete_from_local_when_job_end: true
  file_ext: .csv.gz
  prevent_duplicate_insert: true
  #allow_quoted_newlines: true
  #schema_file: events140681_5826646.json
  schema_update_options:
    - ALLOW_FIELD_ADDITION
    - ALLOW_FIELD_RELAXATION
```

**Comment by sonots** [comment]
Okay, you are getting the error because of

```
prevent_duplicate_insert: true
```

It successfully prevented same job id is issued.

Unfortunately you once failed to load your data because of the bug, set the option to false to load the same data again just for now.

**Comment by liujidong** [comment]
I set the option to false but it did't work,
then I # the option,it also did'it work
the errors:
Error: org.jruby.exceptions.RaiseException: (Error) failed during waiting a Copy job, get_job(vuclipdataflow-1301, embulk_copy_job_d3ba6453-ea13-4ea1-932a-20f1fc7c980f), errors:[{:reason=>"invalid", :message=>"Provided Schema does not match Table vuclipdataflow-1301:amplitude_140681_new.events140681_5826646."}]

how could I avoid delete the tmp table,so I can check the schema of tmp table?

**Comment by sonots** [comment]
You could avoid

> Already Exists: Job

error successfully. The result showed that you backed to the first situation now.

> how could I avoid delete the tmp table,so I can check the schema of tmp table?

No option is available now.

One way is to comment out this line
https://github.com/embulk/embulk-output-bigquery/blob/master/lib/embulk/output/bigquery.rb#L413

Another way is to kill -9 your embulk process before the process deletes the temp table.

**Comment by liujidong** [comment]
why does not it auto add new columns to target table?
I set the temp_table option value to 'append' or 'false',
but it did'it work! I could see the tmp table

thanks

**Comment by sonots** [comment]
It should add new columns. If schema type is different, bigquery errors. As I said, unfortunately, bigquery does not tell us detailed error messages.

**Comment by sonots** [comment]
> I set the temp_table option value to 'append' or 'false',

temp table name will be "append" if you specify "append". It does not help anything.

**Comment by liujidong** [comment]
> Provided Schema does not match Table
> “Provided Schema”? the schema of tmp_table?
> the option schemaUpdateOptions is from configuration.load,dose it work in copying table
> what's the diff between copy and load?

**Comment by sonots** [comment]
Right, and embulk-output-bigquery once loads data into temp table, then copy the temp table to append into target table.

Looking the schema of temp table and target table is a way to find the cause. How to avoid deletion of temp table is as I said before.

**Comment by sonots** [comment]
Ah, you should be able to see the schema of temp table in debug log

**Comment by liujidong** [comment]
yes,I have seen the schema of temp table,the schema has new columns,
but the log still show the not match error when copy the table
It seems that the schemaUpdateOptions did'it work

**Comment by sonots** [comment]
Could you show me the table schema of the temp table and target table? Log and Screenshot of bigquery console UI is fine.

**Comment by liujidong** [comment]
I showed the job and got info like this:
{
  "configuration": {
    "copy": {
      "destinationTable": {
        "datasetId": "amplitude_140681_new", 
        "projectId": "vuclipdataflow-1301", 
        "tableId": "events140681_5826646"
      }, 
      "sourceTable": {
        "datasetId": "amplitude_140681_new", 
        "projectId": "vuclipdataflow-1301", 
        "tableId": "LOAD_TEMP_4a0e5e71_6624_4cf1_9a3e_6f0c6d091d5a_events140681_5826646"
      }, 
      "writeDisposition": "WRITE_APPEND"
    }
  }, 
  "etag": "\"4zcX32ezvFoFzxHoG04qJqKZk6c/XLAtgmWcjJacpdwbFfCc7Kv6ST4\"", 
  "id": "vuclipdataflow-1301:embulk_copy_job_3d66a484-f93e-489c-ae4b-0457408cdceb", 
**but no schemaUpdateOptions 
It seems that the schemaUpdateOptions did'it work**

**Comment by liujidong** [comment]
I did that by bq show -j job_id,
It seems that the schemaUpdateOptions is only support for config.load and config.query not for config.copy

**Comment by liujidong** [comment]
I email to the Google cloud support,
they suggest that I can skip the temporary tables creation step and do the loading of the data directly onto the final tables.
but I can't find any option in config file to skip temporary tables creation
any suggestion?

**Comment by sonots** [comment]
`mode: append_direct` is the one currently supported

**Comment by sonots** [comment]
`mode: delete_in_advance` is also available. It would be good for partitioned table

**Comment by liujidong** [comment]
Other choose is using query job which can support schemaUpdateOptions instead of copy job

**Comment by liujidong** [comment]
Thanks for your message,
mode: append_direct is ok,but that is not transactional as say in README.md
I have written a shell script to check schemas change in redshift and then add columns in bigquery manually
I suggest you consider the query job that support schemaUpdateOptions

**Pull request merged**
