### PR TITLE
Get error message from e.getMessage() instead of e.message (e.getLocalizedMessage())

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/embulk/embulk-output-bigquery/issues/68

@sutoh could you try this?

### CODE REVIEW

**Comment by sutoh** [comment]
@sonots 
Thank you for responding quickly. However, I tried it, but the method did not seem to exist.

```
Exception: embulk-output-bigquery: response:{:message=>"undefined method `getMessage' for #<Google::Apis::ClientError: notFound: Not Found>", :error_class=>NoMethodError}
```


My environment: 
- jruby 2.3.0
- embulk 0.8.15

**Comment by sutoh** [comment]
Sorry, the above comment seems to be wrong with my implementation. I retried the appropriate log, but it was not localized by the e.getMessage () method.
```
2017-05-10 04:03:06.052 +0900 [ERROR] (0001:transaction): embulk-output-bigquery: パイプが切断されました (Write failed)
```

**Comment by sutoh** [comment]
Sorry, the above comment seems to be wrong with my implementation. I retried the appropriate log, but it was not localized by the e.getMessage() method.

e.getMessage()
```パイプが切断されました (Write failed)```

**Comment by sonots** [comment]
Hmm

**Comment by sonots** [comment]
I will try this someday again

**Pull request closed without merging**
