### PR TITLE
Support description of columns and tables

### PR DESCRIPTION
**Pull request by fagai**
related: #127
add tests. and fixed tests.

### CODE REVIEW

**Comment by kyoshidajp** [comment]
@fagai Thank you for adding tests.

**Comment by masaushi** [comment]
Hi, maintainers!
Is this still under review? I need this feature, so I'm hoping this PR will be merged soon.
Thank you maintainers for your time to maintain this project.

**Comment by hiroyuki-sato** [comment]
Hello, @fagai. I'm a new maintainer. Could you resolve conflict this PR? I'll review this PR. Or, I'll create another PR later.

**Comment by fagai** [comment]
@hiroyuki-sato I resolved the conflict.

**Comment by hiroyuki-sato** [comment]
@fagai Thank you for your work!.

Does this PR work as you expected? It seems the column is OK. But, the table doesn't set as you expected. What am I wrong?


```yaml
out:
  type: bigquery
  mode: append
  # snip
  table: hello_embulk
  source_format: NEWLINE_DELIMITED_JSON
  column_options:
  - name: purchase
    description: hogehogehoge12345
  description: hogehoge
```  

## column: OK

スクリーンショット 2024-03-01 22 43 23

## table: NG??

スクリーンショット 2024-03-01 22 43 30

**Comment by fagai** [comment]
@hiroyuki-sato 
Fixed an issue where config values ​​were not being read.

I don't have a deep understanding of ruby, so I may be wrong.

**Comment by hiroyuki-sato** [comment]
Thanks LGTM👍

スクリーンショット 2024-03-03 0 30 08

@joker1007 Could you check this PR when you get a chance?

**Review by hiroyuki-sato — APPROVED** [review]

**Review by joker1007 — APPROVED** [review]

**Comment by hiroyuki-sato** [comment]
Thanks!

**Pull request merged**
